const fs = require("fs")
const path = require("path")

function ensureDirectoryExistence(filePath) {
  var dirname = path.dirname(filePath)
  if (fs.existsSync(dirname)) {
    return true
  }
  ensureDirectoryExistence(dirname)
  fs.mkdirSync(dirname)
}

module.exports = function outputTheme({ config }) {
  const pkgRoot = process.env.PWD || process.cwd()
  const theme = config("theme")
  const outputFile = path.join(pkgRoot, "src/theme.ts")
  process.stdout.write(`Exporting theme to src/theme.ts...`)
  ensureDirectoryExistence(outputFile)
  fs.writeFileSync(
    outputFile,
    `// DON'T MODIFY THIS FILE DIRECTLY
// THIS IS AN AUTOGENERATED FILE IN THE BUILD PROCESS
const theme = ${JSON.stringify(theme, null, 2)}
export default theme`
  )
  process.stdout.write("Done\n")
}
