const fs = require("fs")
const path = require("path")

const iconsDir = path.join(__dirname, "src/icons")
const outFile = path.join(__dirname, "src/index.tsx")

process.stdout.write(`adding imports for icons...`)
fs.writeFile(
  outFile,
  `/**
* ======    DO NOT MODIFY THIS FILE DIRECTLY   =========
* This is an autogenerated file with 'add-imports' and will be overwritten with each build
**/

`,
  function(err) {
    var stream = fs.createWriteStream(outFile, { flags: "a" })
    if (err) throw err
    const modules = []
    fs.readdirSync(iconsDir).forEach(function(file) {
      const from = file.replace(".tsx", "")
      const module = from + "Icon"
      stream.write(`import ${module} from "./icons/${from}"\n`)
      modules.push(module)
    })
    stream.write(`export { ${modules.join(",")}}`)
    stream.end()
    process.stdout.write(`Done\n`)
  }
)
